import { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Button } from "@/components/ui/button";
import heroImage from "@/assets/hero-image.jpg";
import { NavLink } from "@/components/NavLink";

const slides = [
  { badge: "Welcome to Uruhu Solutions", title: "Building Value. Managing Risk", subtitle: "Practical Advisory. Sustainable Value.", description: "A boutique business advisory and solutions firm helping businesses and individuals structure their finances, solve business problems and make informed decisions.", cta1: "Discuss Your Needs", cta2: "Explore Services" },
  { badge: "Who We Are", title: "Turning Complexity into Clarity", subtitle: "Business Insight. Financial Structure. Practical Action.", description: "We bring together business advisory, financial analysis, funding preparation and risk management to help clients move forward with confidence.", cta1: "Our Story", cta2: "Our Services" },
  { badge: "What We Do", title: "Advisory for Better Decisions", subtitle: "Funding Preparation. Risk Advisory. Financial Clarity.", description: "We advise on appropriate options and practical next steps. We do not guarantee funding, investment returns or outcomes.", cta1: "Explore Services", cta2: "Schedule Consultation" },
];

const HeroSection = () => { const [currentSlide, setCurrentSlide] = useState(0); useEffect(() => { const timer = setInterval(() => setCurrentSlide((prev) => (prev + 1) % slides.length), 6000); return () => clearInterval(timer); }, []); const slide = slides[currentSlide]; return <section className="relative flex items-center overflow-hidden pt-24 md:pt-32 min-h-[90vh] md:min-h-screen"><div className="absolute inset-0"><img src={heroImage} alt="Uruhu Solutions" className="w-full h-full object-cover" /><div className="absolute inset-0 bg-gradient-to-b from-navy/95 via-navy/70 to-navy/60" /><div className="absolute inset-0 bg-gradient-to-r from-transparent via-orange/25 to-teal/30" /></div><div className="container-narrow w-full px-4 sm:px-6 md:px-10 lg:px-16 relative z-10 pb-24"><AnimatePresence mode="wait"><motion.div key={currentSlide} initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -20 }} transition={{ duration: 0.5 }} className="max-w-3xl"><span className="inline-flex px-4 py-2 text-xs sm:text-sm rounded-full bg-orange/20 text-white border border-orange/50 backdrop-blur-sm mb-6 font-medium">{slide.badge}</span><h1 className="font-heading text-3xl sm:text-4xl md:text-5xl lg:text-7xl font-bold text-white leading-tight mb-5">{slide.title}</h1><p className="text-lg sm:text-xl md:text-2xl text-teal mb-5 font-semibold">{slide.subtitle}</p><p className="text-base sm:text-lg text-white/90 leading-relaxed mb-10 max-w-2xl">{slide.description}</p><div className="flex flex-col sm:flex-row gap-4"><NavLink to="/contact"><Button size="lg" className="w-full sm:w-auto bg-orange hover:bg-orange-dark text-white font-semibold px-8 py-6 text-base">{slide.cta1}</Button></NavLink><NavLink to="/services"><Button variant="outline" size="lg" className="w-full sm:w-auto border-2 border-teal bg-transparent text-white hover:bg-teal font-semibold px-8 py-6 text-base">{slide.cta2}</Button></NavLink></div></motion.div></AnimatePresence><div className="absolute bottom-8 left-0 right-0 flex items-center justify-center"><div className="flex gap-3">{slides.map((_, i) => <button key={i} onClick={() => setCurrentSlide(i)} className={`h-3 rounded-full transition-all ${currentSlide === i ? "bg-orange w-10" : "bg-white/50 w-3"}`} aria-label={`Go to slide ${i + 1}`} />)}</div></div></div></section>; };
export default HeroSection;
