import { motion, useInView } from "framer-motion";
import { useRef } from "react";
import { Star, Quote } from "lucide-react";

const testimonials = [
  { quote: "Uruhu Solutions brought practical structure and clear thinking to our business decisions, helping us see the next steps with greater confidence.", author: "Usman Abubakar", company: "Blueprint Ltd", rating: 5 },
  { quote: "Uruhu Solutions expertise in financial structuring was instrumental in giving Glowsphere Beauty the solid foundation needed to successfully build our brand. The team delivered strategic guidance on our approach to the brand’s capital strategy and a streamlined path forward.", author: "Precious Ugwu", company: "Glowsphere Beauty", rating: 5 },
  { quote: "The team provided thoughtful asset and portfolio management advisory, helping us evaluate our options and make more informed decisions with a clearer view of risk.", author: "Amara Nwankwo", company: "Casa Prime Properties", rating: 5 },
];

const TestimonialsSection = () => { const ref = useRef(null); const isInView = useInView(ref, { once: true, margin: "-100px" }); return <section id="testimonials" className="section-padding bg-secondary" ref={ref}><div className="container-narrow"><motion.div initial={{ opacity: 0, y: 20 }} animate={isInView ? { opacity: 1, y: 0 } : {}} transition={{ duration: 0.6 }} className="text-center max-w-3xl mx-auto mb-16"><span className="inline-flex items-center px-4 py-2 rounded-full text-sm font-medium bg-teal/10 text-teal border border-teal/20 mb-6">Client Perspectives</span><h2 className="font-heading text-3xl md:text-4xl lg:text-5xl font-bold text-primary mb-4">Practical Advice. Clearer Next Steps.</h2><p className="text-lg text-muted-foreground">Feedback from clients we have supported through business and financial decisions.</p></motion.div><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">{testimonials.map((testimonial, index) => <motion.div key={testimonial.company} initial={{ opacity: 0, y: 30 }} animate={isInView ? { opacity: 1, y: 0 } : {}} transition={{ duration: 0.5, delay: 0.2 + index * 0.1 }} className="bg-card rounded-2xl p-8 shadow-card border border-border relative"><div className="absolute -top-4 left-8"><div className="w-10 h-10 rounded-full bg-orange flex items-center justify-center shadow-orange-glow"><Quote className="w-5 h-5 text-white" /></div></div><div className="flex gap-1 mb-6 mt-4">{[...Array(testimonial.rating)].map((_, i) => <Star key={i} className="w-5 h-5 fill-orange text-orange" />)}</div><blockquote className="text-foreground leading-relaxed mb-6 italic">“{testimonial.quote}”</blockquote><div className="border-t border-border pt-4"><p className="font-heading font-semibold text-primary">— {testimonial.author}</p><p className="text-sm text-muted-foreground">{testimonial.company}</p></div></motion.div>)}</div></div></section>; };
export default TestimonialsSection;
