import { motion, useInView } from "framer-motion";
import { useRef } from "react";
import { Button } from "@/components/ui/button";
import { BriefcaseBusiness, TrendingUp, Shield, PieChart, Check, ArrowRight, Target, Users, LineChart } from "lucide-react";
import heroImage from "@/assets/service-hero2-image.jpg";
import { NavLink } from "@/components/NavLink";

const services = [
  { icon: BriefcaseBusiness, number: "01", title: "Business Advisory & Solutions", tagline: "Building Stronger Businesses Through Better Structure", description: "We help businesses understand their financial position, strengthen operations, improve performance and plan for sustainable growth.", features: ["Business strategy and structuring", "Financial analysis and planning", "Cost and profitability analysis", "Revenue improvement and performance reviews", "Growth and expansion planning", "Management reporting and financial controls"], benefits: ["Clearer financial information", "Better resource allocation", "Stronger operating structures", "More informed decisions", "A practical growth plan"] },
  { icon: TrendingUp, number: "02", title: "Funding & Capital Advisory", tagline: "Preparing Businesses for the Right Capital Opportunities", description: "We assess funding needs and help businesses prepare the financial case, plans and documents required to approach suitable lenders, development finance institutions or investors. We support the application process where appropriate; funding decisions remain with the providers.", features: ["Funding readiness assessment", "Funding strategy and structuring", "Financial models and projections", "Funding plans and application documents", "Use of funds planning", "Debt and equity financing analysis", "Lender and investor presentation materials", "Application preparation support"], benefits: ["Clearer funding requirements", "Stronger financial projections", "Organised documentation", "Better-prepared funding applications"] },
  { icon: Shield, number: "03", title: "Risk Advisory", tagline: "Identifying Risk. Strengthening Resilience.", description: "We help businesses identify and manage financial, operational and regulatory risks while strengthening controls, governance and reporting.", features: ["Enterprise risk assessment", "Financial and credit risk", "Operational risk", "Regulatory and compliance advisory", "Internal controls review", "Risk policies and frameworks", "AML/CFT/CPF advisory", "Risk reporting and business continuity planning"], benefits: ["Greater visibility of material risks", "Stronger controls", "Clearer accountability", "More structured risk reporting"] },
  { icon: PieChart, number: "04", title: "Financial & Investment Advisory", tagline: "Making Better-Informed Financial Decisions", description: "We help clients understand financial goals, evaluate information and build confidence in financial decisions through planning and education. Any personalised investment or asset and portfolio advisory is subject to Uruhu’s confirmation of the necessary permissions and approved scope.", features: ["Financial planning conversations", "Investment education", "General market and risk education", "Business financial analysis", "Capital allocation planning", "Asset and portfolio management advisory, where appropriately scoped"], benefits: ["A clearer view of financial choices", "Better-informed decisions", "Structured planning conversations", "Advice grounded in objectives and risk considerations"] },
];

const processSteps = [
  { icon: Target, title: "Discovery", description: "We understand your business or financial position, goals and challenges." },
  { icon: LineChart, title: "Assessment", description: "We assess the financial, operational and risk considerations that matter to your decision." },
  { icon: Users, title: "Strategy and Structuring", description: "We develop a practical response aligned with your objectives." },
  { icon: TrendingUp, title: "Implementation Support", description: "We support agreed next steps and coordinate with relevant stakeholders." },
];

const ServicesPage = () => {
  const heroRef = useRef(null); const servicesRef = useRef(null); const processRef = useRef(null);
  const heroInView = useInView(heroRef, { once: true, margin: "-100px" }); const servicesInView = useInView(servicesRef, { once: true, margin: "-100px" }); const processInView = useInView(processRef, { once: true, margin: "-100px" });
  return <div className="min-h-screen">
    <section ref={heroRef} className="relative flex items-center overflow-hidden pt-24 md:pt-32 min-h-[90vh]"><div className="absolute inset-0"><img src={heroImage} alt="Uruhu advisory services" className="w-full h-full object-cover" /><div className="absolute inset-0 bg-gradient-to-b from-navy/95 via-navy/85 to-navy/75" /><div className="absolute inset-0 bg-gradient-to-r from-orange/20 via-transparent to-teal/20" /></div><div className="container-narrow w-full px-4 sm:px-6 md:px-10 lg:px-16 relative z-10"><motion.div initial={{ opacity: 0, y: 30 }} animate={heroInView ? { opacity: 1, y: 0 } : {}} transition={{ duration: 0.6 }} className="max-w-4xl"><span className="inline-flex items-center px-4 py-2 rounded-full text-sm font-medium bg-teal/20 text-white border border-teal/50 mb-6">Our Services</span><h1 className="font-heading text-4xl sm:text-5xl md:text-6xl lg:text-7xl font-bold text-white leading-tight mb-5">Services Built Around Better Decisions</h1><p className="text-xl sm:text-2xl text-teal mb-5 font-semibold">Business Advisory. Financial Clarity. Stronger Decisions.</p><p className="text-base sm:text-lg text-white/90 leading-relaxed max-w-2xl">We combine business insight, financial analysis and risk expertise to help clients strengthen operations, prepare for growth and respond to complex decisions.</p></motion.div></div></section>
    <section ref={servicesRef} className="section-padding bg-background"><div className="container-narrow"><div className="space-y-24">{services.map((service, index) => <motion.div key={service.title} initial={{ opacity: 0, y: 30 }} animate={servicesInView ? { opacity: 1, y: 0 } : {}} transition={{ duration: 0.6, delay: index * 0.12 }} className="grid lg:grid-cols-2 gap-12 lg:gap-16 items-center"><div className={index % 2 === 1 ? "lg:order-2" : ""}><div className="flex items-center gap-3 mb-6"><div className="w-16 h-16 rounded-2xl bg-teal flex items-center justify-center shadow-teal-glow"><service.icon className="w-8 h-8 text-white" /></div><span className="text-sm font-bold tracking-widest text-orange">{service.number}</span></div><h2 className="font-heading text-3xl md:text-4xl font-bold text-primary mb-3">{service.title}</h2><p className="text-lg text-teal font-semibold mb-4">{service.tagline}</p><p className="text-muted-foreground leading-relaxed mb-8">{service.description}</p><NavLink to="/contact"><Button className="bg-orange hover:bg-orange-dark hover:shadow-orange-glow text-white font-semibold" size="lg">Discuss Your Needs<ArrowRight className="w-5 h-5 ml-2" /></Button></NavLink></div><div className={index % 2 === 1 ? "lg:order-1" : ""}><div className="bg-secondary rounded-2xl p-8 border border-border"><h3 className="font-heading text-xl font-bold text-primary mb-4">Detailed Offerings</h3><ul className="space-y-3 mb-8">{service.features.map((feature) => <li key={feature} className="flex items-start gap-3"><span className="w-5 h-5 rounded-full bg-orange/20 flex items-center justify-center flex-shrink-0 mt-0.5"><Check className="w-3 h-3 text-orange" /></span><span className="text-foreground">{feature}</span></li>)}</ul><h3 className="font-heading text-xl font-bold text-primary mb-4 pt-6 border-t border-border">What This Supports</h3><ul className="space-y-3">{service.benefits.map((benefit) => <li key={benefit} className="flex items-start gap-3"><span className="w-5 h-5 rounded-full bg-teal/20 flex items-center justify-center flex-shrink-0 mt-0.5"><Check className="w-3 h-3 text-teal" /></span><span className="text-foreground">{benefit}</span></li>)}</ul></div></div></motion.div>)}</div></div></section>
    <section ref={processRef} className="section-padding bg-secondary"><div className="container-narrow"><motion.div initial={{ opacity: 0, y: 20 }} animate={processInView ? { opacity: 1, y: 0 } : {}} transition={{ duration: 0.6 }} className="text-center max-w-3xl mx-auto mb-16"><span className="inline-flex items-center px-4 py-2 rounded-full text-sm font-medium bg-orange/10 text-orange border border-orange/20 mb-6">Our Process</span><h2 className="font-heading text-3xl md:text-4xl lg:text-5xl font-bold text-primary mb-4">How We Work With You</h2><p className="text-lg text-muted-foreground">A structured, transparent approach to practical advice</p></motion.div><div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">{processSteps.map((step, index) => <motion.div key={step.title} initial={{ opacity: 0, y: 30 }} animate={processInView ? { opacity: 1, y: 0 } : {}} transition={{ duration: 0.5, delay: 0.1 + index * 0.1 }} className="relative text-center"><div className="bg-card rounded-2xl p-6 shadow-card border border-border"><div className="w-14 h-14 rounded-full bg-orange flex items-center justify-center mx-auto mb-4 shadow-orange-glow"><step.icon className="w-7 h-7 text-white" /></div><h3 className="font-heading text-lg font-bold text-primary mb-2">{step.title}</h3><p className="text-muted-foreground text-sm">{step.description}</p></div>{index < processSteps.length - 1 && <div className="hidden lg:block absolute top-1/2 -right-4 w-8 h-0.5 bg-teal/30 -translate-y-1/2" />}</motion.div>)}</div></div></section>
    <section className="section-padding bg-gradient-to-br from-navy via-slate to-navy text-white"><div className="container-narrow text-center"><div className="max-w-3xl mx-auto"><h2 className="font-heading text-3xl md:text-4xl font-bold mb-6">Let’s Build What’s Next.</h2><p className="text-lg text-white/80 mb-8">We provide considered advice, not promises. Let’s discuss your objectives and the practical options available to you.</p><NavLink to="/contact"><Button className="bg-orange hover:bg-orange-dark text-white font-semibold" size="lg">Discuss Your Needs</Button></NavLink></div></div></section>
  </div>;
};
export default ServicesPage;
